### PR TITLE
remove empty lines from setup.py

### PR DESCRIPTION
**Pull request by joamatab**

### CODE REVIEW

**Comment by secnot** [comment]
Merged, thank you

**Comment by joamatab** [comment]
awesome, could you make a new release to see if that fixes the issue?

https://github.com/gdsfactory/gdsfactory/runs/4303873877?check_suite_focus=true

**Comment by secnot** [comment]
Does it fix the problem locally?, I can't reproduce the error to verify before a new release.

**Comment by secnot** [comment]
It looks like the problem is with the multi-line string in "long_description", not the spaces in setup.py.

**Comment by joamatab** [comment]
I see, could we shorten the long description and make a new release?

**Comment by secnot** [comment]
I will change it and release it tomorrow, I just need run some integration test before a release, and can't do it today.

**Comment by secnot** [comment]
Ok I was able to test it and realease it, tell me if there is any problem.

**Comment by joamatab** [comment]
Thanks secnot,

it works great now ^^

thank you for your quick response

**Pull request merged**
