### PR TITLE
Improving support of sub-classing

### PR DESCRIPTION
**Pull request by samwyse**
Here's my use-case:

```
class WeightOverride(object):
    def __init__(self, width, height, rot=True, *args, **kwargs):
        self.capacity = kwargs.pop('capacity')
        super(WeightOverride, self).__init__(
            width=width, height=height, rot=rot,
            *args, **kwargs)
    def add_rect(self, width, height, rid=None):
        if self.capacity < rid.weight:
            return None
        rect = super(WeightOverride, self).add_rect(
            width=width, height=height, rid=rid)
        if rect is not None:
            self.capacity -= rid.weight
        return rect

class WtSkylineBlWm(WeightOverride, SkylineBlWm):
    pass

pkr = newPacker(pack_algo=WtSkylineBlWm)

```

Bins have a capacity and bins have a weight.  You mustn't put too heavy a combination of rects into a bin.

### CODE REVIEW

**Comment by secnot** [comment]
I will test it this afternoon but don't see any problem not to merge it.

On an unrelated note, are you using Skyline for packing? Offline or Online mode? Is the algorithm giving good results for your problem?. Because I haven't found the use case where it's the best fit, to the point that I've considered removing the algorithm.  

In my experience **MaxRectsBlsf** (Offline) Is the most stable and produces one of the best packings, but sometimes it's slow (very big bins). **GuillotineBssfSas** (Offline) is faster, a little worse packing (not much), but has greater variation in the quality of the packing.

**Comment by samwyse** [comment]
I am using skyline because it was the default, and I had assumed that the
developer knew what he was doing when he chose it. :-) I haven't tried the
others (except when running the test suite) but I will try to get around to
that sometime this week. Early on, I did do one test, trying to pack four
2x3 rectangles into a 5x5 bin (it's one of my use cases!), and IIRC,
skyline couldn't figure out how to do it.

By the way, I only started playing with the new version the last night but
it looks like it is only filling two bins when using my weight-limiting
packer. Don't know yet if that is my fault.

**Comment by secnot** [comment]
Ok, I've checked, the default algorithm was there before adding maxrects. I have the benchmarks for all  the algorithms and combinations for Offline mode, and the best one overall is the one used by newPacker. (while the average ratio between rectangle sides isn't too extreme)

For Offline mode it should be roughly the same, will redo benchmarks with the same datasets to confirm. (Added Online mode for completeness sake, have never used outside the tests).

About your problem, I don't know what the dominant limiting factor for packing is, If it's the weigh of the rectangle vs bin capacity you will probably end with a lot of half filled bins, I would try to sort the rectangles by descending weight, and the bins by ascending area (if I remember correctly the capacity should be allways the same in your problem).
It all depends on the average area of the bin vs its capacity, and the average area of the rectangles vs their weight. (You could decide what method to use depending on those values)

In the end if the triangle limit is too low for the models you are printing, there is very little you can do:
1. Try to simplify the triangle mesh. I'm sure there are several libs/apps that will do it. And you can use the printer resolution to bound the max allowed error.
2. Print in several batches, each one below the triangle limit
3. Rise the triangle limit with some clever hack :)

**Comment by secnot** [comment]
Added tests and merged into develop branch, I'll keep this open in case you find any problem.

**Pull request merged**
