### PR TITLE
add a way to add as many bins as needed

### PR DESCRIPTION
**Pull request by samwyse**
Add an 'add_factory()' method to store the parameters for a default bin to be used as needed.

Add '*args, **kwargs' to add_factory and add_bin to agree with the __init__ for packing algorithms.

Add '_is_everything_ready()' method to eliminate duplicate code, and include a test for a factory.

### CODE REVIEW

**Comment by secnot** [comment]
This causes an infinite loop when one of the rectangles doesn't fit into the bin, it keeps creating new bins and failing to place the rectangle into them. When a rectangle doesn't fit it should skip all bins with the same dimmensions. 

The original packer has the same problem but all the bins are exausted so there is no infinite loop, it works but it's inefficient. It will modify **_empty_bins** to store dimmensions and number of available bins, then skip empty bins of the same size when packing  a rectangle fails. After that it will be really easy to add bins with infinite members.

Something like this:

```
...
packer.add_bin(55, 55)  
packer.add_bin(59, 80, count=2)  
packer.add_bin(400, 300, infinite=True)
packer.add_bin(600, 600, infinite=True)
...
```

I will try to have a new version by the end of next week. 

And thank you for your contribution.

**Comment by samwyse** [comment]
I think I've got the factory working now, and I've added a lot of comments to the existing code as I figured out what it does.  I also changed the parameters for add_bin (and add_factory) to match those for Packing Algorithms; this is required to support the solution you suggested in issue #1.

I know that you like the "add_bin(infinite=True)" but I think it opens a can of worms since, as in your example, you can create multiple infinite sources of bins.  If nothing else, how do you decide which type of bin to use if a rect would fit into either?  Also, I'm guessing that bins are allocated in the order in which they are added.  In your example above, what happens if we rearrange the order in which the bins are added?  Would some of them never get used even though they're smaller?  Having a single factory that is only used when no suitable bins exist side-steps those types of issues.

**Comment by secnot** [comment]
#### Bin selection

There are different ways to decide which bin is used to pack a rectangle, as you have added to the comments (Thank you by the way):

* **BNF** (Bin Next Fit) - There is only one open bin if the rectangle doesn't fit it is closed and a new one is opened, until it fits in one. (this one is rarely used but is really fast)

* **BFF** (Bin First Fit) - It doesn't close bins, to pack a rectangle  consider the bins in the order they were opened and pack the rectangle into the first bin where it fits.

* **BBF** (Bin Best Fit) - The rectangle is packed into the bin that gives the best fitness score for the
algorithm used. If the rectangle doesn't fit in any of the open bins, a new one where it fits is opened.

* **Global** - For each bin obtain the fitness for all available rectangles, and pack the one with the best ones. Repeat until no more fit into the bin, then open a new one and keep packing until there are no more rectangles or bins. Best and slowest packing selection mode that add O(n) to the computation

When not using **Global** mode where the rectangle order is irrelevant, or **Online** where you don't know the rectangles beforehand, you can also sort them before packing. Depending on your problem can yield even better results:

* **SORT_AREA** - Sort rectangles by area 
* **SORT_PERI** - Sort by perimeter
* **SORT_DIFF** - Sort by difference of sides
* **SORT_SSIDE** - Sort by shortest side
* **SORT_LSIDE** - Sort by longest side
* **SORT_RATIO** - Sort by sides ratio


#### Bin sorting
You could also sort the bins by some criteria before adding them, perhaps you want to fill small bins first, or big bins fins, or you want to fill those with a side much longer than the others.To decide the best combination for your problem you will have to try several alternatives and compare results.

For example If  you had bins with infinite members, it would fill all the *"normal"* bins before the first infinite one is opened, then pack all remaining rectangles into it until one doen't fit, then it would try to pack the rectangle into the follwing bins (that could also be infinite).


#### Heuristic
What I am trying to say is that for each combination of the parameters you will get different results, for some problems the difference can be quite significant with wasted space ranging from 1% to 25%. Bin packing is a NP-complete so this library solution is heuristic, from the packing algorithm to how the bins are chosen, there is no best solution. 

I have implemented the parameters/options that seem to have the biggest impact but many more could be added, for example sorting bins as you mentioned.

#### Infinite
About **"add_bin(infinite=True)"** is my prefered solution because it gives a single interface to add bins instead of two separate funcion, it's less confusing for new user, and easier to maintain. **In essence it is just adding alot of bins for packing**, there is no functional difference for real uses to:
 
```
add_bin(500, 600, count=99999999999999)
```
As you have probably discovered, you needed to create a factory because I was lazy and didn't solve how the bins are evaluated, and ended with an innefficient solution where all bins of the same size are evaluated when it is clear that a rectangle that doens't fit into the first one, it won't fit into the next 99999999999998.

In the end I think we are both saying the same thing.

**Comment by secnot** [comment]
Just finished reading all the code, great job.

**Comment by samwyse** [comment]
You just gave me an idea:

add_bin(500, 600, count=float("Inf"))

And all of our problems are solved!

Seriously, though, I'm starting to think that Packer's add_bin needs to
create bin factories, with the count limiting how many bins each would
create. And I can see the advantages if, say, you're Amazon, with an
infinite number of a few sizes of bins. I'll think on this some more.

**Comment by secnot** [comment]
Hahaha great idea float("Inf"), I was just subclassing a BinFactory class to creat InfBinFactory, much cleaner this way. This way there are no special cases.

**Comment by secnot** [comment]
Pushed first try using BinFactory into **fix-the-bins** branch, still missing alot of tests, and tweaks

**Comment by secnot** [comment]
Fix merged into development branch, after it has been tested successfully for a few weeks I will publish the new package version.

**Pull request closed without merging**
